#stage 1 make the go executable
FROM golang:1.23 AS builder
WORKDIR /dashboard
COPY go.mod .
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o dashboard main.go

#stage 2 copy the go executable and run it
FROM alpine:latest
COPY --from=builder /dashboard/dashboard /dashboard
CMD ["/dashboard"]
